### PR TITLE
added mudskipper main menu functionality

### PR DESCRIPTION
**Pull request by VanessaMedinaUNR**
just needs main code to be put into mudskipper_screen.py file so it can go to mudskipper_house

### CODE REVIEW

**Review by dinaolmelak — CHANGES_REQUESTED** [review]
👍 Seems like you are just getting started with the `ticket`. Keep up the updates to `mudskipper_screen.py`

**Comment by VanessaMedinaUNR** [comment]
> 👍 Seems like you are just getting started with the `ticket`. Keep up the updates to `mudskipper_screen.py`

I have to push my changes so Hannah can access it since we are working together. She now just needs to put her code on the mudskipper scene file.

**Comment by VanessaMedinaUNR** [comment]
> 😄 Don't forget to select your ticket on the right side.
> 
> Screenshot 2023-08-11 at 12 18 58 PM
> 
> 
> 
> Will review your PR in just a moment

I didn't put the ticket because I didn't want to close the ticket once this pill request closed.

**Comment by dinaolmelak** [comment]
It won't close it. It only closes when the PR gets merged to main branch

**Comment by VanessaMedinaUNR** [comment]
> It won't close it. It only closes when the PR gets merged to main branch

Ohhh okay. Will update now then.

**Comment by VanessaMedinaUNR** [comment]
> > It won't close it. It only closes when the PR gets merged to main branch
> 
> Ohhh okay. Will update now then.

updated.

**Review by RuthAnn1 — APPROVED** [review]
Looks good

**Review by dinaolmelak — APPROVED** [review]
👍🏽

**Pull request merged**
