### PR TITLE
Load names

### PR DESCRIPTION
**Pull request by dinaolmelak**
Hello @Techwise-Team-15/everyone ,

In this PR, I incorporated the `load_names` to be used. Please Definitely feel free to pull this PR locally and see how it looks:
```
# Steps for checking out the PR
git checkout -t origin/load_names
```

### CODE REVIEW

**Comment by Donnyd88** [comment]
Looks good, and the back button is nice, but I'm not able to click on the pet name to save them.

**Comment by dinaolmelak** [comment]
I realised, you have to wait like `5 sec` and then click it like 5 times and then click `save`

**Comment by dinaolmelak** [comment]
@Donnyd88  Thank you for checking my PR out

**Comment by dinaolmelak** [comment]
@Donnyd88  I made new changes to it. Please pull and try it again

**Review by Donnyd88 — APPROVED** [review]
@dinaolmelak Looks good. It's working on my end

**Comment by dinaolmelak** [comment]
Thank you

**Pull request merged**
