### PR TITLE
Added bar icons

### PR DESCRIPTION
**Pull request by dinaolmelak**
Just added the bars  for 🥦 , 🥎 , and 🥤 
Bar_labels

### CODE REVIEW

**Review by RuthAnn1 — APPROVED** [review]
Looks good to me.  Makes the bars a lot easier to understand!

**Comment by dinaolmelak** [comment]
Thank you @RuthAnn1 🤔What should be the icon for the `Health` bar?

**Comment by RuthAnn1** [comment]
@dinaolmelak I was thinking may be the red cross like on hospitals?  That is what games normally use.  Thoughts?

**Comment by dinaolmelak** [comment]
🤔 That is a good idea. I can look up and see what I can find that resembles that unless you have like an image for it in mind.

**Comment by RuthAnn1** [comment]
@dinaolmelak No I don't have an image in mind was just thinking that might be the most versatile.

**Comment by dinaolmelak** [comment]
👍🏽 🤔 Ok, Thank you. There might be one that pygame it self might offer or maybe I might do like an emoji next to it.

**Comment by dinaolmelak** [comment]
😅 It is currently printing a little square for the 🏥  emoji @RuthAnn1 
image

**Comment by dinaolmelak** [comment]
@RuthAnn1 I found this icon on the internet and here is the [link](https://www.flaticon.com/free-icon/heart_210545?term=heart&page=1&position=7&origin=search&related_id=210545) 
heart
---
### Here is the License Summary  
Screenshot 2023-07-26 at 10 04 23 PM

**Comment by dinaolmelak** [comment]
I added a heart ❤️ 
heart_added

**Comment by RuthAnn1** [comment]
@dinaolmelak  The heart looks like it would be ok for our game since it says for commercial use.  Sorry it took me a bit today was hectic.  :) The game looks better each day!!

**Comment by dinaolmelak** [comment]
Thank you for the confirmation. 😄 I'm currently occupied with something but I'll go ahead and merge my pull request after 2 hours. Sorry for the delay our  production @Techwise-Team-15/everyone

**Pull request merged**
