### PR TITLE
new spritesheets and items

### PR DESCRIPTION
**Pull request by RuthAnn1**

### CODE REVIEW

**Review by dinaolmelak — COMMENTED** [review]
Thanks for adding these assets and sprites. 🤔 Are we going to also keep the old ones and reroute our existing sprites to these or remove the old sprites and adjust their path to these.

**Review by dinaolmelak — APPROVED** [review]
Looks good! 🙂, we would definitely use these fresh sprites and images

**Review by dinaolmelak — APPROVED** [review]

**Comment by RuthAnn1** [comment]
It could go wither way I suppose.  The new sprite sheets have the rock bathing and getting muddy in different ways.  It also has one drinking water.  I will make a ticket to revamp the pet config files to work with the new sprite sheets.

**Comment by dinaolmelak** [comment]
Yeah, we would need to do that cause it seems like there is an extra frame in there if I am not mistaken 🤔

**Pull request merged**
